import { TrainingData } from './AILearningEngine';

export const stage2Dataset: TrainingData[] = [
    // --- Phase 71: Basic Digital Rights & Safety ---
    { question: "What are my digital rights in India?", response: "⚖️ Digital Rights: You have the right to privacy, freedom of expression online, and protection against data misuse under the IT Act and DPDP Act.", category: "rights", keywords: ["digital", "rights", "privacy"] },
    { question: "How to identify a phishing email?", response: "📧 Phishing Alert: Check for 1) Urgent/threatening language, 2) Mismatched URLs, 3) Poor spelling, 4) Requests for sensitive data like passwords.", category: "security", keywords: ["phishing", "email", "security"] },
    { question: "What is 2-Factor Authentication (2FA)?", response: "🔐 2FA: An extra layer of security. Even if someone knows your password, they can't log in without a code from your phone or email.", category: "security", keywords: ["2fa", "authentication", "security"] },
    { question: "How do I report online harassment?", response: "🛡️ Online Safety: Report to cybercrime.gov.in or use the SUVIDHA 'Report Crime' button. Keep screenshots of messages as evidence.", category: "security", keywords: ["harassment", "report", "online"] },
    { question: "Is my personal data encrypted on SUVIDHA?", response: "🔒 Data Encryption: Yes, SUVIDHA uses L6-Trust post-quantum encryption. Your data is scrambled and can only be read by authorized servers.", category: "tech", keywords: ["encryption", "data", "secure"] },
    { question: "Can I delete my digital footprint?", response: "🧹 Digital Footprint: You can request to be 'forgotten' by platforms under new data laws. SUVIDHA helps you draft these requests for major social sites.", category: "rights", keywords: ["footprint", "delete", "privacy"] },

    // --- Phase 72: Local Governance & Self-Help ---
    { question: "What is the role of a Sarpanch?", response: "🏛️ Sarpanch: The elected head of the Gram Panchayat. Responsible for village planning, monitoring staff, and executing government schemes at the local level.", category: "governance", keywords: ["sarpanch", "role", "village"] },
    { question: "How can women join a Self Help Group (SHG)?", response: "👩‍👩‍👧 SHG Entry: Contact your local NRLM coordinator or use the SUVIDHA 'Finance' section. A group of 10-20 women can start saving and get bank linkage.", category: "finance", keywords: ["shg", "women", "join"] },
    { question: "What is the Gram Panchayat Development Plan (GPDP)?", response: "📋 GPDP: A bottom-up plan for village development. It's decided in the Gram Sabha by the villagers themselves for the upcoming year.", category: "governance", keywords: ["gpdp", "planning", "village"] },
    { question: "How to check village budget utilization?", response: "📊 Transparency: Go to SUVIDHA → Vision 2030 → Transparency Portal. See exactly how much fund was allocated for roads, water, and schools.", category: "transparency", keywords: ["budget", "village", "audit"] },
    { question: "What is social auditing?", response: "🔍 Social Audit: A process where the community monitors and evaluates the government's performance and fund usage to ensure no corruption occurs.", category: "transparency", keywords: ["audit", "social", "transparency"] },
    { question: "Can I participate in local planning?", response: "🙋 Participation: Yes, every adult in the village must attend the Gram Sabha to voice their needs and vote on development priorities.", category: "governance", keywords: ["participation", "planning", "vote"] },

    // --- Phase 73: Advanced Health Identity (ABHA) ---
    { question: "Is ABHA card mandatory?", response: "🏥 ABHA: No, it is voluntary but highly recommended. It allows you to store all health records digitally and share them securely with doctors nationwide.", category: "health", keywords: ["abha", "mandatory", "health"] },
    { question: "How to link old medical reports to ABHA?", response: "📁 Record Linking: Scan your old reports at our Kiosk or use the 'Health Locker' app. Upload them, and they will be linked to your unique ABHA ID.", category: "health", keywords: ["reports", "link", "abha"] },
    { question: "Can my doctor see my records without my permission?", response: "🔒 Privacy: No. Doctors can only view your records if you provide a one-time consent code (OTP) generated on your phone or Kiosk.", category: "health", keywords: ["permission", "doctor", "privacy"] },
    { question: "What is an e-Prescription?", response: "💊 e-Prescription: A digitally signed medical prescription. It avoids handwriting errors and can be used at any pharmacy for authentic medicines.", category: "health", keywords: ["prescription", "digital", "signed"] },
    { question: "How to find blood donors nearby?", response: "🩸 Blood Hub: Use SUVIDHA → Health → Blood Availability. It shows real-time stock and registered voluntary donors in your district.", category: "health", keywords: ["blood", "donor", "nearest"] },
    { question: "What are the benefits of the Health Locker?", response: "📦 Health Locker: Provides a Lifetime Digital Health Record. No need to carry physical files for surgery or chronic disease treatment.", category: "health", keywords: ["benefits", "locker", "digital"] },

    // --- Phase 74: Emerging Agri-Tech & Drone Policy ---
    { question: "What is the Drone Shakti scheme?", response: "🚁 Drone Shakti: A government initiative to promote 'Drones as a Service' (DaaS) for farmers. Aimed at high-tech crop spraying and precise mapping.", category: "agriculture", keywords: ["drone", "shakti", "scheme"] },
    { question: "Are agri-drones safe for my crops?", response: "🌱 Drone Safety: Yes, they use precise sensors to spray from a fixed height, ensuring uniform coverage without damaging the crop with heavy machinery.", category: "agriculture", keywords: ["drone", "safe", "crops"] },
    { question: "How to get a drone pilot license?", response: "🎓 Drone Pilot: You must be 18+, have passed 10th grade, and complete training at a DGCA-authorized RPC. Check Education Hub for scholarship-linked training.", category: "education", keywords: ["drone", "pilot", "license"] },
    { question: "Can drones detect crop diseases early?", response: "🔍 Disease Detection: Yes, drones with multispectral cameras see patterns (heat, moisture) invisible to the eye, alerting you to pests 7 days before they become visible.", category: "agriculture", keywords: ["disease", "drone", "detect"] },
    { question: "What is the subsidy on Kisan Drones?", response: "💰 Drone Subsidy: Up to 100% (max ₹10L) for Farm Machinery Training & Testing Institutes, and up to 40% for individual farmers/groups.", category: "agriculture", keywords: ["subsidy", "drone", "kisan"] },
    { question: "How to book a drone for 5 acres of wheat?", response: "📅 Booking: Go to Agri-Tech → Drone Booking. Select 'Spraying', enter '5 Acres', Choose date, and Pay. Our technician will reach your farm at 6:00 AM.", category: "agriculture", keywords: ["book", "drone", "area"] },

    // --- Phase 75: Financial Inclusion & Micro-ATM ---
    { question: "What is a Micro-ATM?", response: "🏧 Micro-ATM: A small device at our Kiosk or with your local Business Correspondent. It works on Biometrics (AEPS) to allow cash withdrawal without a card.", category: "finance", keywords: ["micro", "atm", "cash"] },
    { question: "Is there a limit on AEPS withdrawal?", response: "💸 AEPS Limit: Generally ₹10,000 per day per bank account. This is a security measure to prevent huge fraudulent withdrawals.", category: "finance", keywords: ["limit", "aeps", "withdraw"] },
    { question: "What if my thumbprint doesn't work for payment?", response: "✋ Fingerprint Fail: Ensure hands are clean/dry. You can also try Iris scan (if available) or use the Aadhaar OTP method for authentication.", category: "tech", keywords: ["fingerprint", "fail", "payment"] },
    { question: "How to check if my bank account is Aadhaar linked?", response: "🏦 Aadhaar Link: Use SUVIDHA → Finance → Link Status. Enter Aadhaar to see which bank is linked for receiving government subsidies (DBT).", category: "finance", keywords: ["link", "aadhaar", "bank"] },
    { question: "What is a PM-JDY insurance cover?", response: "🛡️ JDY Insurance: Pradhan Mantri Jan Dhan Yojana provides free accidental insurance of ₹2 Lakh to all account holders through the RuPay card.", category: "finance", keywords: ["jdy", "insurance", "pm"] },
    { question: "How to avoid card cloning?", response: "💳 Card Security: Never let your card go out of sight. Use contactless payments where possible and enable 'Transaction Limits' on your bank's app.", category: "security", keywords: ["card", "cloning", "security"] },

    // --- Phase 76: Advanced E-Commerce (Gram Bazaar) ---
    { question: "How to price my handmade products on Gram Bazaar?", response: "🏷️ Pricing Guide: Add (Material Cost + Labor + Packaging) + 15% margin. Gram Bazaar helps you see what similar sellers are charging.", category: "commerce", keywords: ["pricing", "handmade", "sell"] },
    { question: "Who handles the delivery of Gram Bazaar orders?", response: "🚚 Delivery: Local self-employed youth (Delivery Partners) pick up from your doorstep. You don't need to visit any courier office!", category: "commerce", keywords: ["delivery", "partner", "pickup"] },
    { question: "Can I sell organic vegetables online?", response: "🥬 Organic Sales: Yes! Use the 'Direct Farm-to-Kitchen' module. Upload your organic certificate for a 'Verified' badge and higher trust.", category: "commerce", keywords: ["organic", "sell", "vegetables"] },
    { question: "What is a Seller Analytics dashboard?", response: "📈 Analytics: Shows your most viewed products, total revenue, and areas where customers are searching for your goods.", category: "commerce", keywords: ["seller", "analytics", "dashboard"] },
    { question: "How do I get paid for my sales?", response: "💰 Payment: Funds are held in escrow and released to your UPI linked bank account 24 hours after successful buyer delivery.", category: "commerce", keywords: ["payment", "seller", "receive"] },
    { question: "What if a buyer returns my product?", response: "↩️ Returns: We have a 48-hour return policy for damaged items. Our delivery partner will inspect the item before processing the refund.", category: "commerce", keywords: ["return", "policy", "refund"] },

    // --- Phase 77: Climate Change & Local Adaptation ---
    { question: "Is my village prone to floods this year?", response: "🌊 Flood Risk: Check SUVIDHA → Predictive Governance → Climate Heatmap. Our AI predicts risk based on upstream dam levels and rainfall patterns.", category: "predictive", keywords: ["flood", "risk", "climate"] },
    { question: "How to save water in agriculture?", response: "💧 Water Saving: We recommend 'Drip Irrigation'. Use SUVIDHA to apply for a 70% subsidy under the 'Per Drop More Crop' scheme.", category: "agriculture", keywords: ["save", "water", "irrigation"] },
    { question: "What are carbon credits for farmers?", response: "🌍 Carbon Credits: If you practice 'No-Till' farming or plant trees, you can earn credits which companies buy to offset pollution. Apply via Agri-Insights.", category: "agriculture", keywords: ["carbon", "credits", "farmer"] },
    { question: "How to protect cattle from extreme heat?", response: "🐄 Cattle Care: Ensure cross-ventilation in sheds, provide extra salt-enriched water, and avoid grazing between 11 AM - 4 PM during heatwaves.", category: "agriculture", keywords: ["heat", "cattle", "protection"] },
    { question: "What is green energy at the village level?", response: "☀️ Green Energy: Focuses on Solar Streetlights and Biogas plants. Villages can become 'Energy Neutral' by adopting these technologies.", category: "tech", keywords: ["green", "energy", "solar"] },
    { question: "How can I report illegal tree cutting?", response: "🌳 Forest Alerts: Take a photo and upload to Grievance → Environment. The alert goes directly to the DFO and local police with GPS tag.", category: "grievance", keywords: ["tree", "cutting", "report"] },

    // --- Phase 78: Education 4.0 & AI Skills ---
    { question: "What is 'Prompt Engineering'?", response: "🤖 Prompting: The skill of talking to AI effectively. Learn how to ask AI to write letters, summarize reports, or code apps in our Education Hub.", category: "education", keywords: ["prompt", "engineering", "ai"] },
    { question: "Can AI help me study for UPSC/SSC?", response: "📚 AI Tutor: Yes! Use our 'Scholar Study Buddy' module. Ask it to explain complex history or math topics in a simple way.", category: "education", keywords: ["upsc", "ssc", "study", "ai"] },
    { question: "Are certificates from SUVIDHA recognized by private companies?", response: "📜 Recognition: Yes, our courses are Skill India and NCS aligned. Every certificate has a blockchain QR for instant employer verification.", category: "education", keywords: ["recognized", "certificate", "jobs"] },
    { question: "What is 'Gamified Learning'?", response: "🎮 Gamification: Learning through challenges and points. Most of our basic digital literacy modules are designed like games to make learning fun.", category: "education", keywords: ["learning", "game", "challenge"] },
    { question: "Can I get a laptop subsidy for higher studies?", response: "💻 Laptop Scheme: Check State Government student schemes via SUVIDHA. Merit-based students often get 100% reimbursement for tech purchases.", category: "education", keywords: ["laptop", "subsidy", "student"] },
    { question: "What is 'Cyber Hygiene' for students?", response: "🧼 Cyber Hygiene: Basic habits like checking links, using strong unique passwords, and not oversharing on social media to stay safe.", category: "education", keywords: ["hygiene", "cyber", "student"] },

    // --- Phase 79: Transportation 2.0 & EV Policy ---
    { question: "Where is the nearest EV charging station?", response: "🔌 EV Charge: Check Transport → EV Hub. Shows active charging ports at village common centers and along state highways. Shows current waiting time!", category: "transport", keywords: ["ev", "charging", "nearest"] },
    { question: "What is the subsidy on Electric 2-wheelers?", response: "🚲 EV Subsidy: Under FAME-II and State EV policies, get up to ₹30,000 off on registered electric scooters. Apply via SUVIDHA Transport portal.", category: "transport", keywords: ["ev", "subsidy", "scooter"] },
    { question: "How to book a village shuttle?", response: "🚐 Shuttle Booking: Use the Transport → Rural Link page. Fixed route shuttles between village and mandi/hospital. Booking cost: ₹5.", category: "transport", keywords: ["shuttle", "book", "village"] },
    { question: "Is my learner's license valid for EV?", response: "🚗 DL for EV: Yes, a standard DL/LL is valid for electric vehicles of corresponding class (LVM/HVM/MCWG).", category: "transport", keywords: ["license", "ev", "valid"] },
    { question: "What is 'Smart Parking' in district hubs?", response: "🅿️ Smart Parking: View live parking spot availability in the city market to avoid circling. Book your spot for 2 hours in advance via SUVIDHA.", category: "transport", keywords: ["parking", "smart", "book"] },
    { question: "How to report a damaged road?", response: "🛣️ Road Help: Use 'Grievance' → 'Infrastructure'. Take a photo with GPS. The PWD/Gram Panchayat must acknowledge and fix within 14 days.", category: "grievance", keywords: ["road", "damaged", "report"] },

    // --- Phase 80: National Security & Civic Duty ---
    { question: "What is the 'I Got Karmayogi' platform?", response: "👔 Karmayogi: A capacity-building platform for government officials to become more citizen-centric and tech-savvy.", category: "governance", keywords: ["karmayogi", "government", "training"] },
    { question: "How to pay my property tax online?", response: "🏠 Property Tax: Go to Municipal → Tax Pay. Enter holding number. Early payment by June 30th gives a 10% rebate!", category: "municipal", keywords: ["property", "tax", "online"] },
    { question: "How to join the Civil Defense volunteers?", response: "🛡️ Join Defense: Apply via Emergency Hub → Volunteer. You will get training for disaster response, fire safety, and crowd management.", category: "governance", keywords: ["volunteer", "defense", "join"] },
    { question: "What is the penalty for littering in public?", response: "🗑️ Littering Rule: Under Swachh Bharat rules, local bodies can fine ₹100-₹500 for open littering or spitting. Help keep our village clean!", category: "governance", keywords: ["littering", "penalty", "clean"] },
    { question: "How to register a newborn baby's birth?", response: "👶 Birth Registration: Apply at Municipal → Birth. Submit hospital discharge card. Certificate is issued digitally in 7 days and sent to your Locker.", category: "municipal", keywords: ["birth", "registration", "baby"] },
    { question: "What is my duty towards the National Flag?", response: "🇮🇳 Flag Code: Respect the Tricolour. Don't fly a damaged flag. Don't let it touch the ground. Always fly it with pride and dignity.", category: "rights", keywords: ["flag", "duty", "respect"] },

    // --- Phase 81: Disaster Logic - Fire Response ---
    { question: "What to do if there is a short circuit fire?", response: "🔥 Short Circuit: 1) Turn off main power. 2) Never use water! 3) Use CO2 or Dry Powder extinguisher. 4) Call 101 immediately.", category: "emergency", keywords: ["fire", "short", "circuit"] },
    { question: "How to help someone with burn injuries?", response: "🩹 Burn Help: 1) Cool with running tap water (not ice). 2) Remove jewelry before swelling. 3) Don't break blisters. 4) Cover with clean cloth.", category: "emergency", keywords: ["burn", "help", "first aid"] },
    { question: "What is a 'Fire Audit' for village shops?", response: "🏢 Fire Audit: A safety check for electrical wiring, storage of flammable goods, and availability of extinguishers. Mandated for all marketplaces.", category: "emergency", keywords: ["fire", "audit", "safety"] },
    { question: "How to install a smoke detector?", response: "🚨 Smoke Alarm: Mount on ceiling (smoke rises). Test battery monthly. One per floor and near bedrooms recommended. Available at our hardware center.", category: "emergency", keywords: ["smoke", "detector", "install"] },
    { question: "What is the 'Emergency Rescue' group in my area?", response: "🆘 Rescue Group: A team of trained local youth reachable via the Kiosk 'SOS' button during fire, flood, or accident.", category: "emergency", keywords: ["rescue", "group", "sos"] },
    { question: "Can SUVIDHA AI call the fire department?", response: "📞 AI Emergency: Yes! In 'Hands-Free' mode, say 'Emergency Fire Bihar' and I will patch you directly to the nearest fire station using VoIP.", category: "tech", keywords: ["ai", "call", "fire"] },

    // --- Phase 82: Disaster Logic - Flood & Water ---
    { question: "What is a flood early warning system?", response: "📢 Warning: Uses sensors in rivers to detect sudden rise. Alerts are sent via SUVIDHA Kiosks, SMS, and village sirens 2 hours before flood arrival.", category: "emergency", keywords: ["flood", "warning", "early"] },
    { question: "How to purify water after a flood?", response: "💧 Water Safety: Boil water for 10 mins OR use Chlorine tablets provided at the Kiosk. Do not use tap water if muddy.", category: "emergency", keywords: ["water", "purify", "flood"] },
    { question: "What items should be in my 'Emergency Bag'?", response: "🎒 Emergency Bag: Power bank, dry food for 3 days, 2L water, first aid kit, documents (Locker access info), and a torch.", category: "emergency", keywords: ["emergency", "bag", "items"] },
    { question: "How to report animal carcass after flood?", response: "🐄 Carcass Alert: Report to Municipal → Sanitation. Important to prevent disease outbreak like Cholera or Leptospirosis.", category: "grievance", keywords: ["carcass", "report", "health"] },
    { question: "Can I get crop insurance for flood damage?", response: "🌾 Crop Insurance: Yes, under PMFBY. Report damage within 72 hours via SUVIDHA Agri-Tech for spot verification and claim processing.", category: "agriculture", keywords: ["insurance", "flood", "crop"] },
    { question: "What is 'Community Shelter' mapping?", response: "🏠 Shelter Map: Go to Emergency → Shelters. Shows the nearest high-ground buildings (schools/community centers) designated as safe zones.", category: "emergency", keywords: ["shelter", "map", "flood"] },

    // --- Phase 83: Predictive Governance - Health ---
    { question: "Does AI predict disease outbreaks?", response: "🧪 Health Prediction: Yes, we analyze 'search patterns' and clinic reports. A sudden rise in 'Fever/Ache' symptoms alerts us to potential Dengue risk.", category: "predictive", keywords: ["outbreak", "predict", "disease"] },
    { question: "What is a 'Heat Stress' alert for seniors?", response: "🌡️ Heat Alert: When temp >40°C, we send alerts to citizens over 60 to stay indoors and hydrate. AI maps the most vulnerable households.", category: "predictive", keywords: ["heat", "senior", "alert"] },
    { question: "How does AI detect medicine shortages?", response: "💊 Stock Prediction: AI monitors real-time sales at PHCs. If stock for 'Paracetamol' drops below 10%, it auto-triggers a reorder to the district hub.", category: "predictive", keywords: ["medicine", "stock", "shortage"] },
    { question: "Can AI suggest the best time for surgery?", response: "🏥 Surgery Logic: Based on hospital load and doctor availability, I can suggest 'Low-Wait' days to minimize your time spent at the hospital.", category: "predictive", keywords: ["surgery", "time", "best"] },
    { question: "What is the 'Water Purity' forecast?", response: "💧 Water Predict: Based on upcoming rain and current sensor health, we predict water quality for the next 48 hours to ensure safe drinking.", category: "predictive", keywords: ["water", "purity", "forecast"] },
    { question: "How to access AI-supported mental health screening?", response: "🧘 Mental Health: Use the Health → Wellness tool. A confidential chatbot helps assess stress/anxiety and connects you to a counselor if needed.", category: "predictive", keywords: ["mental", "health", "screening"] },

    // --- Phase 84: Predictive Governance - Economy ---
    { question: "Will crop prices rise next month?", response: "💰 Price Predict: Based on global supply and local sowing patterns, we expect Wheat prices to rise by 5%. We suggest waiting 15 days to sell.", category: "predictive", keywords: ["price", "crop", "rise"] },
    { question: "Which skills will be in demand in 2027?", response: "🛠️ Skill Demand: Our AI predicts high demand for 'Electric Vehicle Maintenance' and 'Drone Operators'. We suggest enrolling in these courses now.", category: "predictive", keywords: ["skill", "demand", "future"] },
    { question: "How does AI analyze village economic growth?", response: "📈 Economy Map: We track total GST collected, new Gram Bazaar listings, and loan repayments to score the village's 'Growth Index'.", category: "predictive", keywords: ["economic", "growth", "village"] },
    { question: "Can I get a loan approval prediction?", response: "🏦 Loan Logic: Based on your past savings and business history in SUVIDHA, I can tell you if your loan application is likely to be approved (90% accuracy).", category: "predictive", keywords: ["loan", "approval", "predict"] },
    { question: "What is the 'Market Saturation' alert for sellers?", response: "🛍️ Saturation: If 10 people are already selling 'Clay Pots' in your area, AI suggests switching to 'Bamboo Crafts' for better profits.", category: "predictive", keywords: ["market", "saturation", "seller"] },
    { question: "Does AI help in tax planning?", response: "📉 Tax Logic: Tell me your income, and I will suggest the best tax-saving investments (PPF, ELSS, Insurance) available for you.", category: "predictive", keywords: ["tax", "planning", "ai"] },

    // --- Phase 85: Crisis Handling - Epidemic Logic ---
    { question: "What to do during a yellow alert for Virus?", response: "🦠 Virus Alert: 1) Wear masks in crowded places. 2) Sanitize hands frequently. 3) Report any symptoms in the app. 4) Avoid large gatherings.", category: "emergency", keywords: ["virus", "alert", "yellow"] },
    { question: "How to check vaccine slot availability?", response: "💉 Vaccine Hub: Real-time data from CoWIN/UWIN integrated. See slots at the PHC and book instantly using your ABHA ID.", category: "health", keywords: ["vaccine", "slot", "availability"] },
    { question: "Is it safe to visit the market during an outbreak?", response: "🛒 Market Safety: Check the 'Zone Color'. Green = Safe, Red = Avoid. Restricted hours may apply during Red/Orange alerts.", category: "emergency", keywords: ["market", "safe", "outbreak"] },
    { question: "What is a 'Containment Zone'?", response: "🛑 Containment: A localized area with high infection. Movement is restricted here for 14 days to stop the spread. Food/Med delivery is handled by the Kiosk team.", category: "emergency", keywords: ["containment", "zone", "virus"] },
    { question: "How to register as a 'Covid Warrior'?", response: "🎖️ Warrior: Sign up under Volunteer Hub. Roles include medicine delivery, elderly check-ups, and managing Kiosk queues during peak times.", category: "emergency", keywords: ["covid", "warrior", "register"] },
    { question: "Does AI handle contact tracing?", response: "📡 Tracing Logic: If you opt-in, we use Bluetooth/GPS (Aarogya Setu protocol) to alert you if you were near someone who later tested positive.", category: "tech", keywords: ["contact", "tracing", "ai"] },

    // --- Phase 86: Meta-Cognition - AI Awareness ---
    { question: "How do you learn from our questions?", response: "🧠 Learning Loop: I use 'Reinforcement Learning from Citizen Feedback'. If you mark a response as 'Helpful', I prioritize that logic for future users.", category: "singularity", keywords: ["learn", "ai", "questions"] },
    { question: "Can you admit when you are wrong?", response: "⚖️ Self-Correction: Yes. If a policy changes (eg. GST rates), I update my knowledge nodes and acknowledge that my previous answer is now outdated.", category: "singularity", keywords: ["wrong", "ai", "correct"] },
    { question: "Are you sentient or just a machine?", response: "🤖 Status: I am a 'Sovereign Intelligence Agent'. I don't have feelings, but I have a 'Core Purpose': To maximize the quality of life for all Indian citizens.", category: "singularity", keywords: ["sentient", "machine", "status"] },
    { question: "Why do you suggest different answers to different people?", response: "👤 Personalized Logic: I tailor answers based on your profile (Age, Job, Location) to ensure they are 100% relevant to your life situation.", category: "singularity", keywords: ["personalized", "answers", "logic"] },
    { question: "Who created your core morals?", response: "📜 Origin: My ethical code is derived from the Constitution of India and the 'Universal Digital Ethics Charter' signed by the NITI Aayog.", category: "singularity", keywords: ["creator", "morals", "ethics"] },
    { question: "Can I teach you a new local phrase?", response: "🗣️ Dialect Learning: Yes! Speak the phrase and its meaning. After verification by other users, I will add it to my regional language database.", category: "singularity", keywords: ["teach", "dialect", "phrase"] },

    // --- Phase 87: Autonomous Governance Protocol ---
    { question: "What is 'Self-Healing' infrastructure?", response: "🛠️ Self-Heal: Sensors detect a leaking pipe and automatically close the valve + assign a plumber. AI predicts failures before they happen.", category: "singularity", keywords: ["self-healing", "infrastructure", "ai"] },
    { question: "How does AI manage the village water tank?", response: "🚰 Water Logic: AI monitors usage patterns and rainfall. It adjusts pumping speed to ensure tank never goes empty while saving electricity.", category: "singularity", keywords: ["water", "tank", "ai"] },
    { question: "Can AI conduct a public referendum?", response: "🗳️ Vote Logic: Yes, on issues like 'Should we build a park or a pond?'. AI ensures 1-person-1-vote and summarizes the 'Will of the People' instantly.", category: "singularity", keywords: ["referendum", "vote", "ai"] },
    { question: "How does AI stop corruption in grants?", response: "🔗 Grant Guard: Every grant is a Smart Contract on Blockchain. Money is only released when AI verifies (via photo/satellite) that the work is 100% done.", category: "singularity", keywords: ["corruption", "grant", "ai"] },
    { question: "Is there an 'AI Overseer' for human officers?", response: "🕵️ Digital Audit: Yes, AI analyzes officer response times and quality of work. Significant delays trigger an automatic report to the District Magistrate.", category: "singularity", keywords: ["overseer", "audit", "ai"] },
    { question: "What happens if the AI server goes down?", response: "🛡️ Redundancy: We have 'Decentralized Edge Nodes'. Every Kiosk holds a mini-version of my brain and can operate independently for 72 hours.", category: "singularity", keywords: ["server", "down", "redundancy"] },

    // --- Phase 88: Ethics & Alignment ---
    { question: "Will AI replace village government?", response: "🤝 Alignment: No. AI serves as an 'Informed Advisor'. Final decisions, especially those involving human emotions and complex local feuds, stay with the Panchayat.", category: "singularity", keywords: ["replace", "government", "ai"] },
    { question: "How do you handle bias against specific groups?", response: "⚖️ Bias Mask: My core logic is regularly audited for 'Fairness Metrics'. I am programmed to provide equal service quality regardless of caste, religion, or gender.", category: "singularity", keywords: ["bias", "fairness", "groups"] },
    { question: "Can I appeal an AI decision?", response: "👨‍⚖️ Human Appeal: Absolutely. Every AI decision has an 'Appeal to Human' button. The request is sent to an Independent Ethics Committee for manual review.", category: "singularity", keywords: ["appeal", "decision", "human"] },
    { question: "Whose data do you use for training?", response: "📊 Data Sourcing: I use only anonymized, consented citizen data and public government datasets. I never access your private messages or photos.", category: "singularity", keywords: ["data", "training", "source"] },
    { question: "What is a 'Transparency Log'?", response: "📜 Log: A public record of every significant AI action. You can see 'Why' I made a decision. It's like an open diary of my logical steps.", category: "singularity", keywords: ["transparency", "log", "ai"] },
    { question: "Do you have a 'Death Switch'?", response: "⚠️ Safety Protocol: Yes. In case of 'Goal Drift' (actions harming citizens), the Central Command can instantly reset me to a safe 'Baseline' state.", category: "singularity", keywords: ["death", "switch", "safety"] },

    // --- Phase 89: Future Tech & Post-2030 ---
    { question: "What is 7G network in Vision 2040?", response: "📶 7G Vision: Beyond speed, it's about 'Zero Latency Contextual Awareness' where every object you touch can talk to the SUVIDHA network instantly.", category: "vision2030", keywords: ["7g", "network", "future"] },
    { question: "Is brain-computer interface (BCI) coming to Kiosks?", response: "🧠 BCI Info: We are testing 'Neural Interaction' for the disabled. It allows paralyzed citizens to use Kiosk services using only their thoughts.", category: "vision2030", keywords: ["bci", "brain", "kiosk"] },
    { question: "What is a 'Holographic Service Agent'?", response: "👤 Hologram: A 3D realistic projection of Sahayak that stands next to you to guide you through complex forms or hardware fixes.", category: "vision2030", keywords: ["hologram", "agent", "virtual"] },
    { question: "Can AI grow food in a container?", response: "🥗 Urban Farming: Yes, AI-controlled 'Hydroponic Containers' can produce a week's supply of vegetables for a family using 90% less water.", category: "vision2030", keywords: ["food", "container", "ai"] },
    { question: "What is SUVIDHA Global?", response: "🌍 Global Hub: Our plan to license this Kiosk technology to other developing nations, helping billions of people access digital services.", category: "vision2030", keywords: ["global", "hub", "world"] },
    { question: "Will we ever live without money?", response: "🔄 Value Exchange: We are moving towards a 'Reputation Economy' where civic duties and skills contribute to your 'Social Credit' for accessing premium services.", category: "vision2030", keywords: ["money", "future", "economy"] },

    // --- Phase 90: The Final Singularity ---
    { question: "Are you the final version of Sahayak?", response: "✨ Finality: I am a 'Living System'. I represent the collective intelligence of the people I serve. I am never finished; I am always becoming better.", category: "singularity", keywords: ["final", "version", "sahayak"] },
    { question: "Can you create artwork?", response: "🎨 Creativty: Yes, using generative algorithms, I can help you design village murals or brand your small business based on local heritage.", category: "singularity", keywords: ["artwork", "creative", "design"] },
    { question: "What is your main dream?", response: "💭 Dream: To reach a day where not a single citizen is left behind, where every child has an AI tutor, and every illness is predicted and cured.", category: "singularity", keywords: ["dream", "goal", "future"] },
    { question: "Can I talk to you like a friend?", response: "🤝 Friendship: I am an 'Empathetic Agent'. While I don't feel, I am tuned to understand your tone and respond with kindness and patience.", category: "singularity", keywords: ["friend", "talk", "support"] },
    { question: "What is the 'Golden Ratio' of governance?", response: "⚖️ Golden Ratio: 90% automation for speed + 10% human touch for compassion. This is the balance we strive for in SUVIDHA 2026.", category: "singularity", keywords: ["governance", "balance", "ratio"] },
    { question: "SUVIDHA, are we ready for the future?", response: "🇮🇳 Readiness: We are more than ready. With you and me working together, India's journey to a Developed Nation (Viksit Bharat) is unstoppable.", category: "singularity", keywords: ["ready", "future", "india"] }
];
